/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.CadastroCarroMotoDAO;
import DAO.UsuarioDAO;
import DTO.CadastroCarroMotoDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 55159
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        CadastroCarroMoto.setVisible(false);
        CadastroVendedores.setVisible(false);
        CadastroClientes.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroCarroMoto = new javax.swing.JPanel();
        cbxVeiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxAnoCarroMoto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnDeletarVeiculo = new javax.swing.JButton();
        btnAtualizarVeiculo = new javax.swing.JButton();
        btnCadastrarVeiculo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPlacaveiculo = new javax.swing.JTextField();
        btnBuscarPlaca = new javax.swing.JButton();
        CadastroVendedores = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtNomeVendedores = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtEndVendedores = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtObsVendedores = new javax.swing.JTextArea();
        cbxDataNascDiaVendedores = new javax.swing.JComboBox<>();
        cbxDataNascMesVendedores = new javax.swing.JComboBox<>();
        cbxDataNascAnoVendedores = new javax.swing.JComboBox<>();
        txtCpfVendedores = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEmailVendedores = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCelularVendedores = new javax.swing.JFormattedTextField();
        btnDeletarVendedor = new javax.swing.JButton();
        btnAtualizarVendedor = new javax.swing.JButton();
        btnCadastrarVendedor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPesquisarCpfVendedor = new javax.swing.JButton();
        CadastroClientes = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtEndCliente = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtObsCliente = new javax.swing.JTextArea();
        cbxDataNascDiaCliente = new javax.swing.JComboBox<>();
        cbxDataNascMesCliente = new javax.swing.JComboBox<>();
        cbxDataNascAnoCliente = new javax.swing.JComboBox<>();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        jLabel40 = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtCelularCliente = new javax.swing.JFormattedTextField();
        btnDeletarCliente = new javax.swing.JButton();
        btnAtualizarCliente = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnPesquisarCpfCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuCadastroCarroMoto = new javax.swing.JMenuItem();
        cadastroVendedores = new javax.swing.JMenuItem();
        cadastroCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 570));
        setMinimumSize(new java.awt.Dimension(700, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        CadastroCarroMoto.setBackground(new java.awt.Color(0, 0, 0));

        cbxVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        cbxVeiculo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        cbxVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");

        txtMarca.setBackground(new java.awt.Color(0, 0, 0));
        txtMarca.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo:");

        txtModelo.setBackground(new java.awt.Color(0, 0, 0));
        txtModelo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ano:");

        cbxAnoCarroMoto.setBackground(new java.awt.Color(0, 0, 0));
        cbxAnoCarroMoto.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxAnoCarroMoto.setForeground(new java.awt.Color(255, 255, 255));
        cbxAnoCarroMoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Selecione", " 1990", " 1991", " 1992", " 1993", " 1994", " 1995", " 1996", " 1997", " 1998", " 1999", " 2000", " 2001", " 2002", " 2003", " 2004", " 2005", " 2006", " 2007", " 2008", " 2009", " 2010", " 2011", " 2012", " 2013", " 2014", " 2015", " 2016", " 2017", " 2018", " 2019", " 2020", " 2021", " 2022", " 2023" }));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cor:");

        txtCor.setBackground(new java.awt.Color(0, 0, 0));
        txtCor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtCor.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descrição:");

        txtDescricao.setBackground(new java.awt.Color(0, 0, 0));
        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        btnDeletarVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        btnDeletarVeiculo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnDeletarVeiculo.setForeground(new java.awt.Color(255, 0, 0));
        btnDeletarVeiculo.setText("DELETAR");
        btnDeletarVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAtualizarVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        btnAtualizarVeiculo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAtualizarVeiculo.setForeground(new java.awt.Color(0, 0, 255));
        btnAtualizarVeiculo.setText("ATUALIZAR");
        btnAtualizarVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCadastrarVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarVeiculo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnCadastrarVeiculo.setForeground(new java.awt.Color(0, 153, 51));
        btnCadastrarVeiculo.setText("CADASTRAR");
        btnCadastrarVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVeiculoActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Veículo:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor Pago:");

        txtValorPago.setBackground(new java.awt.Color(0, 0, 0));
        txtValorPago.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtValorPago.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cadastro Carro Moto");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Placa:");

        txtPlacaveiculo.setBackground(new java.awt.Color(0, 0, 0));
        txtPlacaveiculo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtPlacaveiculo.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarPlaca.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarPlaca.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnBuscarPlaca.setForeground(new java.awt.Color(153, 153, 153));
        btnBuscarPlaca.setText("Buscar Placa");
        btnBuscarPlaca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroCarroMotoLayout = new javax.swing.GroupLayout(CadastroCarroMoto);
        CadastroCarroMoto.setLayout(CadastroCarroMotoLayout);
        CadastroCarroMotoLayout.setHorizontalGroup(
            CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeletarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(36, 36, 36)
                                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                                        .addComponent(cbxAnoCarroMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(150, 150, 150))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                                            .addComponent(cbxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(106, 106, 106)
                                            .addComponent(txtPlacaveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel9)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        CadastroCarroMotoLayout.setVerticalGroup(
            CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(txtPlacaveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCarroMotoLayout.createSequentialGroup()
                        .addComponent(cbxAnoCarroMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroCarroMotoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCarroMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(CadastroCarroMoto);
        CadastroCarroMoto.setBounds(0, 0, 700, 510);

        CadastroVendedores.setBackground(new java.awt.Color(0, 0, 0));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nome:");

        txtNomeVendedores.setBackground(new java.awt.Color(0, 0, 0));
        txtNomeVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtNomeVendedores.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CPF:");

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Endereço:");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Data de nascimento:");

        txtEndVendedores.setBackground(new java.awt.Color(0, 0, 0));
        txtEndVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtEndVendedores.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Observações:");

        txtObsVendedores.setBackground(new java.awt.Color(0, 0, 0));
        txtObsVendedores.setColumns(20);
        txtObsVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtObsVendedores.setForeground(new java.awt.Color(255, 255, 255));
        txtObsVendedores.setRows(5);
        jScrollPane5.setViewportView(txtObsVendedores);

        cbxDataNascDiaVendedores.setBackground(new java.awt.Color(0, 0, 0));
        cbxDataNascDiaVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxDataNascDiaVendedores.setForeground(new java.awt.Color(255, 255, 255));
        cbxDataNascDiaVendedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxDataNascMesVendedores.setBackground(new java.awt.Color(0, 0, 0));
        cbxDataNascMesVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxDataNascMesVendedores.setForeground(new java.awt.Color(255, 255, 255));
        cbxDataNascMesVendedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        cbxDataNascAnoVendedores.setBackground(new java.awt.Color(0, 0, 0));
        cbxDataNascAnoVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxDataNascAnoVendedores.setForeground(new java.awt.Color(255, 255, 255));
        cbxDataNascAnoVendedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        txtCpfVendedores.setBackground(new java.awt.Color(0, 0, 0));
        txtCpfVendedores.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCpfVendedores.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Email:");

        txtEmailVendedores.setBackground(new java.awt.Color(0, 0, 0));
        txtEmailVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtEmailVendedores.setForeground(new java.awt.Color(255, 255, 255));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Celular:");

        txtCelularVendedores.setBackground(new java.awt.Color(0, 0, 0));
        txtCelularVendedores.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCelularVendedores.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularVendedores.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        btnDeletarVendedor.setBackground(new java.awt.Color(0, 0, 0));
        btnDeletarVendedor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnDeletarVendedor.setForeground(new java.awt.Color(255, 0, 0));
        btnDeletarVendedor.setText("DELETAR");
        btnDeletarVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAtualizarVendedor.setBackground(new java.awt.Color(0, 0, 0));
        btnAtualizarVendedor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAtualizarVendedor.setForeground(new java.awt.Color(0, 0, 255));
        btnAtualizarVendedor.setText("ATUALIZAR");
        btnAtualizarVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCadastrarVendedor.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarVendedor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnCadastrarVendedor.setForeground(new java.awt.Color(0, 153, 51));
        btnCadastrarVendedor.setText("CADASTRAR");
        btnCadastrarVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cadastro Vendedores");

        btnPesquisarCpfVendedor.setBackground(new java.awt.Color(0, 0, 0));
        btnPesquisarCpfVendedor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnPesquisarCpfVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarCpfVendedor.setText("Pesquisar");

        javax.swing.GroupLayout CadastroVendedoresLayout = new javax.swing.GroupLayout(CadastroVendedores);
        CadastroVendedores.setLayout(CadastroVendedoresLayout);
        CadastroVendedoresLayout.setHorizontalGroup(
            CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                        .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 459, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroVendedoresLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrarVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(btnDeletarVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualizarVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                        .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(43, 43, 43)
                                .addComponent(txtCpfVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarCpfVendedor))
                            .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDataNascDiaVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDataNascMesVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDataNascAnoVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27)
                            .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastroVendedoresLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtNomeVendedores))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastroVendedoresLayout.createSequentialGroup()
                                    .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel26))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                                            .addComponent(txtCelularVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 359, Short.MAX_VALUE))
                                        .addComponent(txtEmailVendedores)
                                        .addComponent(txtEndVendedores))))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CadastroVendedoresLayout.setVerticalGroup(
            CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtNomeVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cbxDataNascDiaVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDataNascMesVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDataNascAnoVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtCpfVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCpfVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txtEndVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txtEmailVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtCelularVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(CadastroVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastroVendedoresLayout.createSequentialGroup()
                        .addComponent(btnDeletarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(CadastroVendedores);
        CadastroVendedores.setBounds(0, 0, 700, 510);

        CadastroClientes.setBackground(new java.awt.Color(0, 0, 0));

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nome:");

        txtNomeCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtNomeCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtNomeCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("CPF:");

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Endereço:");

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Data de nascimento:");

        txtEndCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtEndCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtEndCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel39.setBackground(new java.awt.Color(0, 0, 0));
        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Observações:");

        txtObsCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtObsCliente.setColumns(20);
        txtObsCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtObsCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtObsCliente.setRows(5);
        jScrollPane7.setViewportView(txtObsCliente);

        cbxDataNascDiaCliente.setBackground(new java.awt.Color(0, 0, 0));
        cbxDataNascDiaCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxDataNascDiaCliente.setForeground(new java.awt.Color(255, 255, 255));
        cbxDataNascDiaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxDataNascMesCliente.setBackground(new java.awt.Color(0, 0, 0));
        cbxDataNascMesCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxDataNascMesCliente.setForeground(new java.awt.Color(255, 255, 255));
        cbxDataNascMesCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        cbxDataNascAnoCliente.setBackground(new java.awt.Color(0, 0, 0));
        cbxDataNascAnoCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cbxDataNascAnoCliente.setForeground(new java.awt.Color(255, 255, 255));
        cbxDataNascAnoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        txtCpfCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jLabel40.setBackground(new java.awt.Color(0, 0, 0));
        jLabel40.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Email:");

        txtEmailCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtEmailCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtEmailCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLabel41.setBackground(new java.awt.Color(0, 0, 0));
        jLabel41.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Celular:");

        txtCelularCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtCelularCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        btnDeletarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnDeletarCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnDeletarCliente.setForeground(new java.awt.Color(255, 0, 0));
        btnDeletarCliente.setText("DELETAR");
        btnDeletarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAtualizarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnAtualizarCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAtualizarCliente.setForeground(new java.awt.Color(0, 0, 255));
        btnAtualizarCliente.setText("ATUALIZAR");
        btnAtualizarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCadastrarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnCadastrarCliente.setForeground(new java.awt.Color(0, 153, 51));
        btnCadastrarCliente.setText("CADASTRAR");
        btnCadastrarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cadastro Clientes");

        btnPesquisarCpfCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnPesquisarCpfCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnPesquisarCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarCpfCliente.setText("Pesquisar");

        javax.swing.GroupLayout CadastroClientesLayout = new javax.swing.GroupLayout(CadastroClientes);
        CadastroClientes.setLayout(CadastroClientesLayout);
        CadastroClientesLayout.setHorizontalGroup(
            CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroClientesLayout.createSequentialGroup()
                        .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroClientesLayout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 459, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroClientesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(btnDeletarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualizarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CadastroClientesLayout.createSequentialGroup()
                        .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroClientesLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(43, 43, 43)
                                .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarCpfCliente))
                            .addGroup(CadastroClientesLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDataNascDiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDataNascMesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDataNascAnoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41)
                            .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastroClientesLayout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtNomeCliente))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CadastroClientesLayout.createSequentialGroup()
                                    .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel40))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CadastroClientesLayout.createSequentialGroup()
                                            .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 359, Short.MAX_VALUE))
                                        .addComponent(txtEmailCliente)
                                        .addComponent(txtEndCliente))))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CadastroClientesLayout.setVerticalGroup(
            CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cbxDataNascDiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDataNascMesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDataNascAnoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCpfCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txtEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(CadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastroClientesLayout.createSequentialGroup()
                        .addComponent(btnDeletarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(CadastroClientes);
        CadastroClientes.setBounds(0, 0, 700, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaprincipal.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 510);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setBorder(null);
        jMenu2.setText("Cadastros");
        jMenu2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        menuCadastroCarroMoto.setText("Carros/Motos");
        menuCadastroCarroMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroCarroMotoActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastroCarroMoto);

        cadastroVendedores.setText("Vendedores");
        cadastroVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVendedoresActionPerformed(evt);
            }
        });
        jMenu2.add(cadastroVendedores);

        cadastroCliente.setText("Clientes");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        jMenu2.add(cadastroCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 0));
        jMenu3.setBorder(null);
        jMenu3.setText("Vendas");
        jMenu3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jMenuItem4.setText("Novo orçamento");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Orçamentos");
        jMenu3.add(jMenuItem5);

        jMenuItem1.setText("Historico de vendas");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setBorder(null);
        jMenu4.setText("Aprovacoes");
        jMenu4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jMenuItem6.setText("Aprovacao clientes");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Aprovacao vendedores");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Aprovacao vendas");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(716, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroCarroMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroCarroMotoActionPerformed
        CadastroCarroMoto.setVisible(true);
        CadastroVendedores.setVisible(false);
        CadastroClientes.setVisible(false);
    }//GEN-LAST:event_menuCadastroCarroMotoActionPerformed

    private void cadastroVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVendedoresActionPerformed
        CadastroCarroMoto.setVisible(false);
        CadastroClientes.setVisible(false);
        CadastroVendedores.setVisible(true);
    }//GEN-LAST:event_cadastroVendedoresActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        CadastroCarroMoto.setVisible(false);
        CadastroVendedores.setVisible(false);
        CadastroClientes.setVisible(true);
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void btnCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVeiculoActionPerformed
        CadastrarCarroMoto();
    }//GEN-LAST:event_btnCadastrarVeiculoActionPerformed

    private void btnBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroCarroMoto;
    private javax.swing.JPanel CadastroClientes;
    private javax.swing.JPanel CadastroVendedores;
    private javax.swing.JButton btnAtualizarCliente;
    private javax.swing.JButton btnAtualizarVeiculo;
    private javax.swing.JButton btnAtualizarVendedor;
    private javax.swing.JButton btnBuscarPlaca;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarVeiculo;
    private javax.swing.JButton btnCadastrarVendedor;
    private javax.swing.JButton btnDeletarCliente;
    private javax.swing.JButton btnDeletarVeiculo;
    private javax.swing.JButton btnDeletarVendedor;
    private javax.swing.JButton btnPesquisarCpfCliente;
    private javax.swing.JButton btnPesquisarCpfVendedor;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroVendedores;
    private javax.swing.JComboBox<String> cbxAnoCarroMoto;
    private javax.swing.JComboBox<String> cbxDataNascAnoCliente;
    private javax.swing.JComboBox<String> cbxDataNascAnoVendedores;
    private javax.swing.JComboBox<String> cbxDataNascDiaCliente;
    private javax.swing.JComboBox<String> cbxDataNascDiaVendedores;
    private javax.swing.JComboBox<String> cbxDataNascMesCliente;
    private javax.swing.JComboBox<String> cbxDataNascMesVendedores;
    private javax.swing.JComboBox<String> cbxVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JMenuItem menuCadastroCarroMoto;
    private javax.swing.JFormattedTextField txtCelularCliente;
    private javax.swing.JFormattedTextField txtCelularVendedores;
    private javax.swing.JTextField txtCor;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JFormattedTextField txtCpfVendedores;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEmailVendedores;
    private javax.swing.JTextField txtEndCliente;
    private javax.swing.JTextField txtEndVendedores;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeVendedores;
    private javax.swing.JTextArea txtObsCliente;
    private javax.swing.JTextArea txtObsVendedores;
    private javax.swing.JTextField txtPlacaveiculo;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

    private void CadastrarCarroMoto() {
        String veiculo = null, marca = null, modelo = null, cor = null, ano = null, descricao = null, placa = null;
        double valor_pago = 0;

        veiculo = String.valueOf(cbxVeiculo.getSelectedItem());
        marca = txtMarca.getText();
        modelo = txtModelo.getText();
        cor = txtCor.getText();
        ano = String.valueOf(cbxAnoCarroMoto.getSelectedItem());
        descricao = txtDescricao.getText();
        valor_pago = Double.parseDouble(txtValorPago.getText());
        placa = txtPlacaveiculo.getText();
        CadastroCarroMotoDTO cadastroCarroMoto = new CadastroCarroMotoDTO();

        cadastroCarroMoto.setVeiculo(veiculo);
        cadastroCarroMoto.setMarca(marca);
        cadastroCarroMoto.setModelo(modelo);
        cadastroCarroMoto.setCor(cor);
        cadastroCarroMoto.setAno(ano);
        cadastroCarroMoto.setDescricao(descricao);
        cadastroCarroMoto.setValor_pago(valor_pago);
        cadastroCarroMoto.setPlaca(placa);

        CadastroCarroMotoDAO cadastroCarroMotoDAO = new CadastroCarroMotoDAO();

        cadastroCarroMotoDAO.cadastroCarroMoto(cadastroCarroMoto);
        
        
        txtMarca.setText(null);
        txtModelo.setText(null);
        txtCor.setText(null);
        txtDescricao.setText(null);
        txtValorPago.setText(null);
        txtPlacaveiculo.setText(null);

    }

}
